/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      colors: {
        "on-secondary-container": "#e8fbff",
        "secondary-fixed": "#26e6ff",
        "on-surface": "#f1f3fc",
        "on-error-container": "#ffb2b9",
        "on-primary-fixed": "#000000",
        "tertiary-fixed": "#bda1ff",
        "tertiary-fixed-dim": "#b190ff",
        "outline": "#72757d",
        "secondary-dim": "#00d4ec",
        "surface-container": "#151a21",
        "surface-variant": "#20262f",
        "secondary": "#00e3fd",
        "secondary-fixed-dim": "#00d7f0",
        "on-secondary-fixed-variant": "#005964",
        "on-secondary": "#004d57",
        "primary-container": "#ff5eec",
        "surface": "#0a0e14",
        "on-background": "#f1f3fc",
        "primary-fixed": "#ff5eec",
        "error-container": "#a70138",
        "secondary-container": "#006875",
        "on-primary": "#590053",
        "on-secondary-fixed": "#003a42",
        "outline-variant": "#44484f",
        "error-dim": "#d73357",
        "surface-container-lowest": "#000000",
        "surface-tint": "#ff7eeb",
        "on-primary-fixed-variant": "#550050",
        "on-error": "#490013",
        "surface-container-highest": "#20262f",
        "on-primary-container": "#450041",
        "primary-fixed-dim": "#ff2bef",
        "tertiary-dim": "#874cff",
        "surface-dim": "#0a0e14",
        "on-surface-variant": "#a8abb3",
        "tertiary": "#ac89ff",
        "inverse-primary": "#ac00a2",
        "surface-bright": "#262c36",
        "on-tertiary": "#290067",
        "inverse-surface": "#f8f9ff",
        "on-tertiary-container": "#f8f1ff",
        "primary": "#ff7eeb",
        "tertiary-container": "#7000ff",
        "primary-dim": "#ff56ed",
        "surface-container-high": "#1b2028",
        "error": "#ff6e84",
        "on-tertiary-fixed": "#1f0052",
        "background": "#0a0e14",
        
        teal: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          200: '#99f6e4',
          300: '#5eead4',
          400: '#2dd4bf',
          500: '#14b8a6',
          600: '#0d9488',
          700: '#0f766e',
          800: '#115e59',
          900: '#134e4a',
          950: '#042f2e',
        },
      },
      animation: {
        'glow': 'glow 2s ease-in-out infinite alternate',
        'float': 'float 3s ease-in-out infinite',
        'slide-up': 'slideUp 0.3s ease-out',
        'fade-in': 'fadeIn 0.4s ease-out',
        'eq-1': 'eqBar 0.8s ease-in-out infinite alternate',
        'eq-2': 'eqBar 0.6s ease-in-out infinite alternate 0.2s',
        'eq-3': 'eqBar 0.9s ease-in-out infinite alternate 0.1s',
        'eq-4': 'eqBar 0.7s ease-in-out infinite alternate 0.3s',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
      },
      keyframes: {
        glow: {
          '0%': { boxShadow: '0 0 5px rgba(20, 184, 166, 0.2)' },
          '100%': { boxShadow: '0 0 20px rgba(20, 184, 166, 0.4)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        eqBar: {
          '0%': { height: '4px' },
          '50%': { height: '100%' },
          '100%': { height: '6px' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}